### PR TITLE
sws-2020-01

### PR DESCRIPTION
**Pull request by nofishonfriday**
cumulative merge of currently open PRs #1237 - #1321

not merged yet:
- ~#1258 (waiting for additions from cfillion)~ (merged)
<del>- #1262 (would like to request review)</del> merged
- #1291 ~~(waiting for decision)~~ for after v2.12
- #1301, ~~#1304~~ (waiting for review, discussion etc.) #1304 merged

TODO:
- curate whatsnew.txt
in progress: https://gist.github.com/nofishonfriday/f2b91d92ca11ea107fa898fabe8230a9
<del>- bump version</del> (done, https://github.com/reaper-oss/sws/pull/1288/commits/f028265ffbb287cbcca9209c543bffa7c1ba3947)
<del>set min. required REAPER version to v5.982 (see https://github.com/reaper-oss/sws/issues/1240#issuecomment-562893473)</del> (done, 21180070)

### CODE REVIEW

**Comment by nofishonfriday** [comment]
squashed the commits of PR #1270

**Comment by nofishonfriday** [comment]
@cfillion 
I got merge conflicts when merging #1290 because of #1270.
I resolved them manually and think it should be ok, but if you want to double-check..

**Comment by cfillion** [comment]
>  #1258 (waiting for additions from cfillion)

Done, however I messed up the git push so the code is in my fork's `breeder-grid-actions` branch.

>  #1262 (would like to request review)

Looks good to me! (I like the void to MediaTrack replacement.)

>  #1291 (waiting for decision)

I think the filter syntax improvement can wait after 2.12.

>  #1301, #1304 (waiting for review, discussion etc.)

Reviewed #1304.

**Comment by nofishonfriday** [comment]
Thanks. Branch and whatsnew updated.
(I merged your breeder-grid-actions branch too. If it gets revised according to Breeder feedback, the changes could be push forced.)

**Pull request merged**
