### PR TITLE
GetUsedCCLanes() to return (Bank/Program Select) upon PC

### PR DESCRIPTION
**Pull request by icalvo**
Fix for #1344

### CODE REVIEW

**Comment by icalvo** [comment]
> Thanks for the PR!
> 
> https://github.com/reaper-oss/sws/pull/1345/files#diff-a084b794bc0759e7a6b77810e01874f2
> 
> I once had a conversation with @cfillion about adding these to .gitignore, quoting his opinion here:

Makes sense. I didn't even know about `.git/info/exclude`, thanks! I will revert the `.gitignore`.

**Comment by icalvo** [comment]
Can we add that `.gitignore` insights to the Wiki? Not sure how to do it myself.

**Comment by nofishonfriday** [comment]
> Can we add that .gitignore insights to the Wiki? Not sure how to do it myself.

Good idea.
Suggestion:

> About included .gitignore file:
> .gitignore only includes files generated as part of the build process.
> So local config files/folders (such as .vscode, .vs/, CMakeSettings.json) are purposely not included.
> Contributers may add those to their user-wide .gitignore or .git/info/exclude for sws-specific personal ignore rules (see e.g. [here](https://help.github.com/en/github/using-git/ignoring-files)).

Anything to change/add?

**Comment by icalvo** [comment]
I didn't refer to the wording (although yours seems perfect to me) but to how to add things to the Wiki. It doesn't let me edit the pages.

**Comment by nofishonfriday** [comment]
Thanks, added.

**Comment by cfillion** [comment]
Merged into `master` as bb55a817de35bfbfab389930108aa056207cefd9.

**Pull request closed without merging**
