### PR TITLE
2019 01

### PR DESCRIPTION
**Pull request by X-Raym**
Hi,

This is a temptative to merge all current PR to SWS next.

It did build successfully and it seems to work.

Also, it has been updated for VS 2017, and taglib has been updated for that.

Here is a build test if you want to test : https://drive.google.com/open?id=1GjyDJTHsBntEy5gVSMy3KC6NkODROCwz

Let me know if it miss something !

EDIT: I missed the newest PR after https://github.com/reaper-oss/sws/pull/1076, but I'm not sure they are ready. @cfillion @nofishonfriday

### CODE REVIEW

**Comment by nofishonfriday** [comment]
@X-Raym 
Thanks.
The whatsnew.txt could be made a bit nicer I think. :)
Like a unified 'Fixes' section, a unified 'New ReaScript functions' section etc (like done for the previous version) .
I could do that too if you want.
Also @cfillion's changes seem missing currently. 

My remaining PR's are ready for merge and shouldn't cause any merge conflicts, so if you could add these that would be nice.

**Comment by X-Raym** [comment]
> Also @cfillion's changes seem missing in the whatsnew.txt currently.

Hmmm maybe he didn't change whatsnew.txt file in his PR. So this text will definitely need manual intervention. Let's merge all PR first (waiting for cfillion answer about his last one).

**Comment by cfillion** [comment]
Wow, 15,283 changed lines! 🎉 

I can write changelog lines for my PRs if necessary (didn't do it thinking to avoid merge conflicts).

- Changes to  `SanitizeFilename` from #1061  got lost in the merges, causing this PR to fail to build on non-Windows systems (I tested on Linux) and the bug to not be completely fixed (at least the part that addresses the crash survived, but rendering these regions wouldn't work).
- Changes to `WritePrivateProfileString` from #1037 also got lost. Looks like d0191d1d56632b7922deb3b250432757ca4dc6a5 moved the keyName check to another function.
- #1042 fails to build on Linux with recent gcc (oops), I fixed it.
- 7d537897f79d312dd0622d106770df98be6977e7 changes indentation in parts of cfillion.cpp, making it inconsistent... http://i.imgur.com/vOWAAUK.png
- I think Tim uses VS2013 for release build? In which case e7cf9cc3cbb55d3217000b740639005072f1b5b8 could be problematic. If updating to VS2017 for release builds: WDL must be patched in order not to break SWS's auto-update: https://github.com/cfillion/WDL/commit/5d678d2d04af7c0bb3d3d55bb1aecf3e82ad08d2.patch. https://forums.cockos.com/showthread.php?t=195247

There might be other unintended regressions due to the mass merging...

**Comment by nofishonfriday** [comment]
I'm not sure how we proceed at this point but in case it's helpful here's a patch (applicable to X-Raym's fork/2019-01 branch) which re-adds the lost changes from points one and two of @cfillion's comment above, along with some other minor changes.

[re-sws-pull-1092-#issuecomment-455864800-patch.zip](https://github.com/reaper-oss/sws/files/2776908/re-sws-pull-1092-.issuecomment-455864800-patch.zip)

**Comment by X-Raym** [comment]
> I think Tim uses VS2013 for the release build?

VS 2017 is cross platform and freely available. It worth updating :)

> unnoticed regressions due to the mass merging

I deeply hope its the last time we have to do that. It is so confusing.

Now I have to find how to merge your updated PR back to this fork. 😨 

@nofishonfriday I'm not sure what I have to do with this patch ?

**Comment by X-Raym** [comment]
@cfillion https://i.imgur.com/bQYNxCi.gif I don't see your update from GitHub, not sure what is wrong here.

**Comment by nofishonfriday** [comment]
> @nofishonfriday I'm not sure what I have to do with this patch ?

You can 'apply patches' similarly as you 'merge PRs'
(sorry if I'm telling already known stuff)

Are you using a graphical Git client?
I use [SourceTree](https://www.sourcetreeapp.com/) there it's easy, as there is a 'Apply patch' function.
Otherwise you can also do it from command line, e.g.
https://coderwall.com/p/yeh5tw/how-to-create-and-apply-a-patch-with-git

**Comment by X-Raym** [comment]
@nofishonfriday I have the feeling GitHub App desktop is way too basic for this PR project.

**Comment by X-Raym** [comment]
Beautiful

**Comment by cfillion** [comment]
> I don't see your #1061 update from GitHub, (or the other PR) not sure what is wrong here.

I've only updated #1042 today (replaced two commits with new ones). Re-merging it should work (you will likely get a conflict).

The missing changes from the other two PRs (#1061 & #1037) got lost while merging additional PRs/resolving conflicts. nofish's patch above adds them back.

**Comment by nofishonfriday** [comment]
Here are the formatted changes for whatsnew.txt from my side:
https://gist.github.com/nofishonfriday/fd1d23014a6b1504caefe289790986b3

@cfillion 
You could use as basis for adding yours if you want.

**Comment by cfillion** [comment]
> You could use as basis for adding yours if you want.

Done: https://gist.github.com/cfillion/eff126ff7a17ed1be50602cbd669b3e3/revisions#diff-3347828e9afab30934620106c0fbd0be.

(Maybe the changes in each sections should be sorted alphabetically?)

**Comment by nofishonfriday** [comment]
@X-Raym 
You're welcome for SourceTree.

> Merge remote-tracking branch 'github-desktop-nofishonfriday/Loudness_-_add_'high_precision'_analyzing_mode' into 2019-01

I think I didn't actually open a PR for this one, or did I? (maybe I forgot) :D
Originally I planned not to add this to coming SWS version as there's already so much new stuff in there, but now that you've merged already, ok.
But please don't also merge the other branches in my repo which don't have have an open PR, as there are also some WIP branches not yet ready for merging.

**Comment by X-Raym** [comment]
@nofishonfriday My bad, I was looking about non merge PR, and the source tree vizualisation show me some 'unmerged' forks so I started merging before cfillion makes me realize that these were not PR. 😄 But it's isn't too bad !

**Comment by nofishonfriday** [comment]
@X-Raym 
No problem.
>  I wonder if I didn't missed any PR,

From my side, what's missing currently (and is ready for merging):
PRs #1081, #1083, #1090
Sidenote (for future):
I think it's a good idea to make the first commit message line as meaningful as possible to see at a glance what's going on.
Example:
https://i.imgur.com/UO41mlc.jpg
doesn't tell much at first glance :)

@cfillion 
> Done: https://gist.github.com/cfillion/eff126ff7a17ed1be50602cbd669b3e3.
> (Maybe the changes in each sections should be sorted alphabetically?)
Thanks. I'll do the alphabetical sorting.
What about your fix for #1086 btw.?
I'd find that rather important to be also contained (unless fixed in Reaper meanwhile, but it's at least not in current Reaper pre/dev yet.)

**Comment by X-Raym** [comment]
All nofish current working PR have been merged. @nofishonfriday but you still have some branch where you just put some cleane up code, I let you check and go back until early 2017 to be sure all you want to be merge has been considered for this release.

@cfillion Let us know about yours :) I think this https://github.com/cfillion/sws/tree/relative-pdb is your first non PR branch, are your that all the branch which haven't been push as PR are not ready for this release ?

**Comment by nofishonfriday** [comment]
@X-Raym 
Already replied at #1090 before I saw your comment here.
I've gone through again and think that's it indeed.

**Comment by nofishonfriday** [comment]
I tried building on OSX from X-Raym's fork (https://github.com/X-Raym/sws/commit/78625ad5e3b3b3b224689251ca4acf273b7d4af9)

A few issues (if we want to keep current build environment, Tim is using XCode v3.x.6. I think, I tried with XCode 5.1)
- The merged C++11-ify commit (cffed96e2b33c7fd5d1d6236e4c624785081b6e7) breaks
- nullptr instead of NULL breaks
- XCode project must be updated to add the new RenderRegion.h/.cpp files and remove the obsolete RenderTrack.h/.cpp files (same probably for Linux makefile)
- some other small things

Patches which should fix these:
[NF_OSX_fixes.zip](https://github.com/reaper-oss/sws/files/2781019/NF_OSX_fixes.zip)

@cfillion 
If you could look over them that  would be nice.
With these changes applied the only OSX compile error still present is [this line](https://github.com/X-Raym/sws/blob/2019-01/cfillion/cfillion.cpp#L274l) I think.

**Comment by cfillion** [comment]
Thanks for testing on macOS. Indeed, my optional C++11 commit should be reverted (cffed96e2b33c7fd5d1d6236e4c624785081b6e7).

I fixed `REAPER_cue` being initialized using C++11 syntax in 24ae3f600ac14e58d1dc6e6436dd489783743839 (updated PR #1011).

Looks like changes to Misc/TrackSel.cpp from patch1.diff breaks these new actions because `nextTrID` and `prevTrID` are still used for `CSurf_TrackFromID` but are no longer incremented. Another way to fix the warning is:

```diff
- for (nextTrID; nextTrID <= GetNumTracks(); nextTrID++)
+ for (; nextTrID <= GetNumTracks(); nextTrID++)
```

@X-Raym Here are three additional patches to fix the inconsistent indentation introduced in 7d537897f79d312dd0622d106770df98be6977e7, uncomment a compile-time check for VS2017 and update the Linux Makefile for the new RenderRegion.cpp: https://gist.github.com/cfillion/4c47c2704266fce01b7c3b07936bc717.

**Comment by X-Raym** [comment]
@cfillion @nofishonfriday Merged !
So what I have to do now is to revert cffed96 ?

**Comment by X-Raym** [comment]
OK so it seems everything which needed to be merge has been merge.

It can compile on Win. Does it work for OSX / linux @nofishonfriday ?

If it is all good, I'll contact Tim !

**Comment by nofishonfriday** [comment]
> So what I have to do now is to revert cffed96 ?
EDIT: What would be the git command for that ?

That's already done in my unified patch you applied.
https://github.com/X-Raym/sws/commit/6bbcf91414969de724f93c5477526239a9a7c96b#diff-55d436c47954d30944849b1f950b71d6

But generally, in SourceTree you can rightclick a commit > there should be an option that says 'Revert..'

I'll test again on OSX again soon with the new commits and report back.

**Comment by nofishonfriday** [comment]
> Looks like the changes to Misc/TrackSel.cpp from patch1.diff breaks these new actions...

Duh, thanks.
@X-Raym 
here's a patch for it:
[sel_nearest_prev_nxt_folder-fix-incr-decr_patch.zip](https://github.com/reaper-oss/sws/files/2784903/sel_nearest_prev_nxt_folder-fix-incr-decr_patch.zip)

@X-Raym, @cfillion 
OSX build from https://github.com/X-Raym/sws/commit/27f5f0aaded429c228704cd073a17886eb421f3e
works fine. :)
These are now the only warnings I get:
osx build from 27f5f0aaded429c228704cd073a17886eb421f3e

cfillion.cpp
lines 256, 275

BR_ContextualToolbars.cpp
line 941

**Comment by X-Raym** [comment]
@nofishonfriday updated with your patch !

**Comment by nofishonfriday** [comment]
Thanks.
Then I'll finilaze (alphabetisze) the whatsnew.txt soon, if @cfillion's changes are all in?
And that should be it then for contacting Tim?

Also, @cfillion, maybe that got lost in the communication, wanted to ask again about your fix for #1086, as I didn't see that in the commits.

**Comment by nofishonfriday** [comment]
@X-Raym 
There's a new branch in my repo
https://github.com/nofishonfriday/sws/tree/taglib-vs15-clean-up

Could you merge it please?

**Comment by X-Raym** [comment]
@nofishonfriday it should be good !

Anything else ?

@cfillion It seems you commit to https://github.com/cfillion/sws/tree/fxchain-hwnd yesterday, is it for merging with this PR ?

**Comment by nofishonfriday** [comment]
Thanks.
That's it from my side I think, [whatsnew.txt](https://gist.github.com/nofishonfriday/fd1d23014a6b1504caefe289790986b3) is also ordered / finalized (needs to be integrated in your branch when cfillion is also done).

So let's see what cfillion thinks about contacting Tim.

**Comment by cfillion** [comment]
@nofishonfriday 
> What about your fix for #1086 btw.?
I'd find that rather important to be also contained (unless fixed in Reaper meanwhile, but it's at least not in current Reaper pre/dev yet.)

It's incompatible with both #991 and #960 as it stands currently. Also the API's ghost points may or may not be a REAPER bug... I think the fix should wait another cycle to have time to be properly re-worked.

> These are now the only warnings I get: [...] cfillion.cpp lines 256, 275

Yeah I noticed those: fixed in 79fe14fd60ad6f3e4720791ccf2180e72291f2b9 above. 😄 

> That's it from my side I think, whatsnew.txt is also ordered / finalized (needs to be integrated in your branch when cfillion is also done).

Looks fine by me. The only changes I've omitted are #1001, #1050, #1051 and #1096 which I don't think are worth mentioning.

@X-Raym 

I've sent you a PR with additional cleanups. Most notably removing reascript_vararg.h from source control (it's a build artifact generated at compile time, not part of the source code).

> It seems you commit to https://github.com/cfillion/sws/tree/fxchain-hwnd yesterday, is it for merging with this PR ?

These changes (`s/nullptr/NULL`) were already in nofish's 6bbcf91414969de724f93c5477526239a9a7c96b (which is included in this PR). 

> Let us know about yours :) I think this https://github.com/cfillion/sws/tree/relative-pdb is your first non PR branch, are your that all the branch which haven't been push as PR are not ready for this release ?

My non-PR branches are personal, WIP or abandoned, but my old `relative-pdb` branch might be useful as it prevents the full path of the local SWS repository to be included in the .dll... Submitted as PR #1096.

**Comment by X-Raym** [comment]
@nofishonfriday @cfillion what version number do you want ? 2.10 ?

@nofishonfriday the whatnew you sent me miss the special markup to say the new version and seperators between version.

**Comment by cfillion** [comment]
Just noticed we're updating taglib on Windows, but not on macOS. Also it's disabled on Linux (`-DNO_TAGLIB`).

Perhaps this update (from to ) should be noted in the changelog as well?

**Comment by X-Raym** [comment]
@cfillion I added "- TagLib VS 2017 update for Windows" in the changelog in Other Changes sections.

**Comment by X-Raym** [comment]
@nofishonfriday @nofishonfriday Version updated !

Ready to contact Tim ?

**Comment by cfillion** [comment]
I think it should be a pre-release. Is bumping the minimum REAPER version necessary (at a glance I don't see we're requiring new API functions)?

**Comment by X-Raym** [comment]
@cfillion oh, it's minimum REAPER version ?

Hmmm, as we don't have tested on earlier REAPER version, I think it is safer to ask for bump anyway.

But I can regress if necessary.

--

I'm afraid that if this go to pre-relealse, it will wait for months like the last v2.9.8 version without ever going official.

**Comment by nofishonfriday** [comment]
> It's incompatible with both #991 and #960 as it stands currently. Also the API's ghost points may or may not be a REAPER bug... I think the fix should wait another cycle to have time to be properly re-worked.

Hm, I don't feel very happy with this tbh.
It means we would release a version that has potential to screw up projects.
https://forum.cockos.com/showthread.php?p=2081909#post2081909
(Ok, so does current sws version also, so it wouldn't be a 'new' bug.)

Fixes always before new features for me. :)
Would be fine for me if we reverted #960 for it. 
With #991 I'm also not very happy anyway that it's merged tbh (I discussed with X-Raym already when he started the merging), as I think it's an incomplete implementation (it doesn't really make BR_Envelope stuff work with AIs from what I could gather.)

What do you think?

**Comment by nofishonfriday** [comment]
@X-Raym 

> I added "- TagLib VS 2017 update for Windows" in the changelog in Other Changes sections.
please add / change

> TagLib VS 2017 update for Windows (from 1.6.3. to v1.11.1)

**Comment by X-Raym** [comment]
@nofishonfriday 

> It means we would release a version that has potential to screw up projects.

Screwing projects happens when the actions modify .rpp chunks in a bad ways, in our cases, I think the worst scenarios will lead to a function having a bug, not a project corruption, so people could still choose to stay on v2.9.8 if there is something which pass our long and extensive test filters.

I don't say this is 100% our release will have no introduced bugs, I just think it's good to stimulate the hype around project on the user side to have a new official release, as long as it is not dangerous for the user (and I don't think it is).

But if you both think it should be pre-release, then it will be pre-release.

And if you are not sure about #960 and #991 I'll sure will revert these commit.

**Comment by X-Raym** [comment]
@nofishonfriday this should be good but a close look at the whatnew is necessary, cause I wonder if commit like  - Contextual toolbars: Add Automation item context (Issue 915) are still valid (I think I saw function related to that in #960 revert. Reversing a branch merge can lead to quite more confusion than merging.

**Comment by nofishonfriday** [comment]
@X-Raym, @cfillion 

I thought about this again after some sleep (sorry if previous comment came across a bit negative)
Suggestion:
How about we mail Justin, explaining the issue and that we're shortly before a new SWS release, asking if Cockos intends to fix on their side?
To me it would be worth the wait.

**Comment by cfillion** [comment]
@nofishonfriday 

Knowing whether it's truly a bug on REAPER's side would certainly remove a lot of uncertainties!

I can now confirm that editing envelopes by their chunks is slower than using the API (I did a bit more testing this morning), but it's negligible for real-life sized envelopes (< 500k points). I'm OK with including the patch without #991 and #960 (especially if the API's fake points turns out to be a "live with it" feature).

@X-Raym 

> I'm afraid that if this go to pre-relealse, it will wait for months like the last v2.9.8 version without ever going official.

I think it's dangerous to mark such a large release as "stable" without giving it some time for real-life testing first. It's worse if fixes have to take months before being officially released.

(It shouldn't be forgotten that the current stable 2.9.7 release is badly broken with some REAPER installs and 2.9.8 has a few regressions. It might be a good idea to ship a slightly patched 2.9.8 as stable.)

**Comment by nofishonfriday** [comment]
@cfillion, @X-Raym 
Done mailing Justin asking about it (and suggesting to join in here).
I'll report back if he answers via mail.

@cfillion 
Thanks for reconsidering (if it turns out to be a 'live with it'), appreciated.

> I think it's dangerous to mark this as "stable" without giving it some time for real-life testing first. It's worse if fixes have to take months before being officially released.
+1

> I hope all this merging adventure will lead to more regular updates cause it will be really hard to managed on the long run.
This also. :)

**Comment by cfillion** [comment]
@X-Raym sws_extension.vcxproj broke in 90baa47cc: it contains unresolved conflict markers. I've sent you a PR (X-Raym/sws#2).

**Comment by X-Raym** [comment]
@cfillion Merged !

**Comment by nofishonfriday** [comment]
@X-Raym 
> but a close look at the whatnew is necessary,

Indeed, with https://github.com/reaper-oss/sws/pull/960 merge reverted, the complete section '+Mouse context: Initial support for automation items:' needs to be removed.

**Comment by X-Raym** [comment]
@nofishonfriday removed !

Is there anything you want to add for envelope according to Justin's answer ?

**Comment by X-Raym** [comment]
I found a bug in #950, we can discuss this issue there.

**Comment by cfillion** [comment]
Mhh we can't just ignore points if they are at or within an AI's boundaries because they may be real points...

**Comment by nofishonfriday** [comment]
@cfillion 
> Mhh we can't just ignore points if they are at or within an AI's boundaries because they may be real points... 

If I understand correctly, that's an issue when implementing Justin's suggestion?
If so, couldn't we use the parsing approach from you instead, or is there also a problem with it?

> unless BR_Envelope should abstract automation items away: transparently handling their points as if they were in the underlying envelope

That's what I also started implementing [here](https://github.com/nofishonfriday/sws/blob/BR_Envelope%2C_BR_EnvelopeUtil_-_make_functional_with_automation_items_(WIP)/Breeder/BR_EnvelopeUtil.cpp#L1842)

But it has the same problem currently, not being able to get the points/pointcount reliably, because of the CountEnvelopePoints() quirk.

**Comment by X-Raym** [comment]
@nofishonfriday rather than editing your post, you should leave new comment so we can get a notification ;P
Also did you take a look at #950 ?

**Comment by nofishonfriday** [comment]
> rather than editing your post, you should leave new comment so we can get a notification ;P
Will do. Certainly in ongoing conversations, in this case I thought since it*s the most recent comment you'll see it anyway sooner or later. :)

> Also did you take a look at #950
I awaited some more info from you, steps to reproduce?

Btw, from now I may be out of coding and rather rare here for about a week or so due to personal stuff.

**Comment by X-Raym** [comment]
@nofishonfriday Steps to reproduce are exposed there : https://github.com/reaper-oss/sws/pull/979#issuecomment-457760578

Basically it is just "have group enables" and use the function a single item of a group : they will all be edited (which is unexpected). SO the fix should only having group disable in the SetItemEdges function and restore back to original state.

> Btw, from now I may be out of coding and rather rare here for about a week or so due to personal stuff.

Ok I hope you'are fine !

**Comment by nofishonfriday** [comment]
Sorry, I missed that comment.
Should be straightforward, I'll do in the next day(s).

> Ok I hope you'are fine !
Thanks. No worries, just moving room and some other organisational things. :)

**Comment by cfillion** [comment]
Submitted my patch as PR #1098 (and added an additional cleanup commit–hoping it doesn't break anything). It does not add support for AIs, but at least it fixes the existing functionality.

**Comment by X-Raym** [comment]
@cfillion Merged.

Any other consideration to... consider ? 😄 

The good news is that we will (afte rmerge) be able to delete a loooot of branches. This will make things cleaner.

**Comment by X-Raym** [comment]
@nofishonfriday what should it be labeled ?

**Comment by cfillion** [comment]
"Fix envelope reconstitution when automation items are connected to the underlying envelope"

**Comment by X-Raym** [comment]
@cfillion @nofishonfriday Time to contact @swstim then :P

**Comment by X-Raym** [comment]
@nofish @cfillion
Our PR is now official 2.10.0 release !
Well done ! :D

We safely delete a lot of branches and makes things cleaner. Cool !

**Comment by nofishonfriday** [comment]
Thanks to you too for starting the big merging initiative. :)

**Pull request merged**
