### PR TITLE
sws-2019-09

### PR DESCRIPTION
**Pull request by nofishonfriday**
cumulative merge of (almost, see below) all currently open PRs
what's not merged yet:
~~- #1111, #1163 - conflicting commits in BR_EnvelopeUtil.cpp (chunking vs. API), wouldn't want to decide on my own which to merge..~~
merged #1163 (https://github.com/reaper-oss/sws/pull/1195/commits/8be88b617787e0615ebc31bb638abf7a9483d956)
~~- #1186 - got merge conflict in SnM_RegionPlaylist.cpp~~
merged #1186 (https://github.com/reaper-oss/sws/pull/1195/commits/739ab3cb628f2de67aae400f73c41877ac125073)
- #1112 - not crucial

merged #1197 (https://github.com/reaper-oss/sws/pull/1195/commits/d9b66004154913de90b743252ef1e7e5f179c5e9)
merged #1202 (https://github.com/reaper-oss/sws/pull/1195/commits/e1cad7fd4a9b3ea83579c434869cbfd583f5b083)
merged #1203 (https://github.com/reaper-oss/sws/pull/1195/commits/5d45e0924756904db5f6da4cc37cd78879819716)

~~TODO:~~
~~- bump minimum REAPER version to v5.979 (https://github.com/reaper-oss/sws/pull/1195#issuecomment-531038414)~~
~~- curate whatsnew.txt~~
~~in progress:~~
https://gist.github.com/nofishonfriday/efc32c9c37953a7ba1abb2701eadddee

### CODE REVIEW

**Comment by cfillion** [comment]
> Sure, but how so? You mean opening a PR for it on my repo or should I add you as collaborator?

All collaborators gain write access to submitted pull request's branches when the "Allow edits from maintainers" checkbox is ticked. I can send a PR if you prefer too.

> Maybe ~ a month is a bit short for keeping SWS backwards compatibility with older Reaper versions?

Yeah, one month is bit too tight for no real good reason.

> I had some conflicts when reverting the chunking in b35a744 which I think came from 24e79b1 which I tried to keep intact, so it would be good if you could look over it.

Looks good to me!

**Comment by nofishonfriday** [comment]
> All collaborators gain write access to submitted pull request's branches when the "Allow edits from maintainers" checkbox is ticked. I can send a PR if you prefer too.

Ah, news to me.
I see it's ticked already, so go ahead. :)

> Looks good to me!
Thanks for checking. So I'll merge https://github.com/reaper-oss/sws/pull/1163 shortly.

Then I'd also merge #1197 (if it's fine), curating (new word I learned in this context :D) the whatsnew.txt, I could do, and then it should be ready for proposing Time to merge?

**Comment by nofishonfriday** [comment]
@cfillion 
Sorry for the confusion.
I merged your PR #1200 before I noticed you have already pushed to this branch.
Then I didn't know how to cleanly reverse it, so I made a hard reset and added your commits as patch again.

**Comment by cfillion** [comment]
Mhh I'm not sure what happened either (I only pushed here once before your merge of 'envelope-tweaks'), but it looks like the merge was successful before the last force-push? You should be able to reset the history to how it was then using `git reset --hard  e443823`.

**Comment by nofishonfriday** [comment]
> You should be able to reset the history to how it was then using git reset --hard e443823. 
Done, thanks.
For future, it's fine if you push to it, I just have to remember to check for updates before I do something with it.

> I'd like to land a fix for #1189
I'm also currently looking into #1158 and the likely too small envelope buffers used in [TrackSends.cpp](https://github.com/reaper-oss/sws/blob/6963f7563851c8dd919db426bae825843939077f/ObjectState/TrackSends.cpp#L275-L295). I think I can improve thanks to your code snippet from Slack, so no hurry. :)

**Comment by nofishonfriday** [comment]
@cfillion 
(almost) ready for contacting Tim for merging?
If you want to look over the whatsnew and change / add something:
https://gist.github.com/nofishonfriday/efc32c9c37953a7ba1abb2701eadddee

version bump (as it's mostly bug fixes):?
```
#define SWS_VERSION 2,10,1,0
#define SWS_VERSION_STR "2, 10, 1, 0\0"
#define SWS_VERSION_TYPE "Pre-release"
#define SWS_COMMIT "@GIT_COMMIT@"
#define REA_VERSION 5,9,7,9
```

**Comment by cfillion** [comment]
> (almost) ready for contacting Tim for merging?

Yes!

Whatsnew's formatting is looking good (makewhatsnew.exe outputs https://fiddle.jshell.net/dsw2uzyh/show/). Sublists are not parsed but this is not new (a markdown whatsnew could be nice instead of the custom format in the future?)

> send envelopes should now be stored/recalled correctly with Snapshots (long standing bug), **thogh** it hasn't been tested much

Small typo there.

> (internal): BR_Envelope::Build(), BR_Envelope::Commit(): revert to using API envelope code (rather than chunking)

I don't think this line is useful to most users (and us devs have the git log for this kind of historical info). The changelog already mentions the only user-visible change earlier (p=2094872) and 2.10.0's changelog only mentionned the fix for #1086.

> split the macOS release into 32-bit and 64-bit versions, delete reaper_sws_extension.dylib

Users will see this if they install reaper_sws-x86_64.dylib or reaper_sws-i386.dylib without deleting the old reaper_sws_extension.dylib:

Screenshot

Same on Linux actually (new filenames without an installer to automate the migration).

I think adding a note like this would be helpful:

> <strong>Update notice:</strong> The SWS extension filenames have changed in this release. Linux and macOS users should remove the previous version before installing SWS X.Y.Z.

Speaking of which, the new ARM linux builds should be mentioned (it's also the motivation for the new filenames, since it makes suffixes like "32" or "64" insufficient):

> +Added Linux ARM builds (32-bit and 64-bit)

---

> version bump (as it's mostly bug fixes)?

I think calling it 2.11.0 would be worth it. There's more than just backward-compatible bugfixes (just bumping the REAPER version makes it not backward-compatible) and it's not a tiny update after all: 62 commits, 93 files and 3k lines are changing in this PR alone. 😄

**Comment by nofishonfriday** [comment]
done.
If you give 'go' I'd contact Tim! :)

**Comment by cfillion** [comment]
Go

**Pull request merged**
