### PR TITLE
BR Mouse context: don't detect envelope segment when mouse cursor is outside of automation items bounds and underlying envelope is bypassed

### LINKED ISSUE #1488: envelope contextual toolbar opens where there is no envelope
thanks for your software!

i have had unpredictable behavior with contextual toolbars for a while, and finally found out why.

if you have AI in the media lane with background envelope disabled, and if you -

1 - move mouse cursor vertically over an empty track area while triggering "SWS/BR: Exclusive toggle contextual toolbar under mouse cursor, preset [n]"

2 - you will see that the "envelope" context gets triggered at the position where the last envelope point existed, even though there is no envelope context under mouse cursor.

see this. you can tell the "envelope" toolbar by the "move on/move off" text, and the "arrange" toolbar by the grid options.

https://i.imgur.com/zhsOaU9.gif

### LINKED ISSUE #1727: reaper.BR_GetMouseCursorContext() reports envelope segment even when mouse cursor is out of AI bounds
1) change REAPER prefs to show track envelopes in automation items only, with underlying envelope disabled and disconnected from the AIs.

2) then use reaper.BR_GetMouseCursorContext() on the track, outside of the AI bounds.

issue: reaper.BR_GetMouseCursorContext() reports "envelope segment" when it is mousing over items or empty space outside of the AI bounds.

see gif here:
https://imgur.com/O77i8Nk

probably related: sws contextual envelopes also overlook disconnected AIs. 

https://github.com/reaper-oss/sws/issues/1488

### PR DESCRIPTION
**Pull request by nofishonfriday**
fixes #1727, fixes #1488

\# BR_EnvelopeUtil.h: add link to schwa's post listing AI tokens

Seems to work:
env det

```
function main()
  window ,segment, detail = reaper.BR_GetMouseCursorContext()
  reaper.defer(main)
end

main()
```

### CODE REVIEW

**Comment by cfillion** [comment]
7e3b8c775e89df1ca5320cb970964248682be055 adds a lot of trailing whitespace:

Trailing whitespace

**Comment by nofishonfriday** [comment]
Oops, not sure how that happened, thanks.
Could/will fix in ~6 hours, but if you're currently in the process of merging and like to do it earlier go ahead. :)

**Comment by Buy-One** [comment]
Would be nice to have the new behavior documented for the end users.

**Comment by cfillion** [comment]
> Would be nice to have the new behavior documented for the end users.

It's a bugfix for incorrectly detecting an envelope segment where there are none when "Bypass underlying envelope outside of automation items" is enabled:

Before

With this PR applied:
After

**Comment by Buy-One** [comment]
Ah OK, misunderstood, thought it was new feature of ignoring segments of a bypassed envelope

**Pull request merged**
