### PR TITLE
sws-2-12-1

### PR DESCRIPTION
**Pull request by nofishonfriday**
cumulative merge of currently open (fixing) PRs #1342 - #1424

not merged:
~~#1414 (WIP)~~ merged
~~- #1343 not a fix + not sure it's worth it?~~ merged
~~- #1364 not a fix, but maybe trivial enough to merge?~~ merged

TODO:
~~- curate whatsnew.txt~~
~~- bump version~~

### CODE REVIEW

**Comment by cfillion** [comment]
>    #1343 not a fix + not sure it's worth it?
>    #1364 not a fix, but maybe trivial enough to merge?

I think these are both good to be merged, even if they're not strictly bugfixes. #1364 does a code cleanup/bugfix (arguably)/new minor feature all in one go. 😄

**Comment by cfillion** [comment]
The changes to vendor/WDL got lost during the merging of the HiDPI and localization PRs.

**Comment by nofishonfriday** [comment]
Hm..yeah just noticed too.
Can I run `git submodule update` and commit/push that or should I start anew with the merging?

**Comment by cfillion** [comment]
Fixed, along with the changes to the P_EXT, ConfigVar and BR_Envelope cleanup PRs.

I didn't edit the whatsnew.txt in each merge to avoid conflict hell if further rebasing is necessary. I curated the whatsnew for 2.12.1 in a new commit (to be amended if new entries/changes are to be made).

Do you have anything else you'd like to add for 2.12.1? I added everything that was on my TODO list.

(I think the track lock zoom PR should wait until the next cycle because it's a non-trivial feature change that will need much testing for edge cases.)

**Comment by nofishonfriday** [comment]
> I didn't edit the whatsnew.txt in each merge to avoid conflict hell if further rebasing is necessary.
Yeah, that's probably the better way to do it. :) (Will do so too in the future, I just was a little afraid whatsnew entries may get lost/forgotten to add if not done directly with the merge..).

> I think the track lock zoom PR should wait until the next cycle because it's a non-trivial feature change that will need user testing for edge cases.

Hm..wouldn't it be better we 'ship' with a bugfix that needs testing than with a (imo not minor) bug:
https://forum.cockos.com/showthread.php?t=205372

**Comment by cfillion** [comment]
Ah yes, the part that fixes the height lock being ignored deserves to be included. Do you think the final commit could be split into separate commits for the important bugfix, refactoring of DoSelTraxHeight{A,B} and the new obey track lock feature?

**Pull request merged**
