### PR TITLE
Add snooks section with FocusMIDIEditor API function and action

### PR DESCRIPTION
**Pull request by Lazzle**
Just adds a simple function to help MID scripters.

### CODE REVIEW

**Comment by swstim** [comment]
Cool, thanks.

The following needs to be done before I can merge:
- BuildUtils/build_template_langpack.sh
- whatsnew.txt
- Linux Makefile
- Your file headers with the proper filename/copyright year
- Add localization support with //!WANT_LOCALIZE_1ST_STRING_BEGIN:sws_actions //!WANT_LOCALIZE_1ST_STRING_END keywords.

If you aren't sure how to do any of these no worries, I will do it myself, but it'll be a few days.

**Comment by Lazzle** [comment]
No probs, will do. You don't happen to know off the top of your head how to focus a window that's docked in the docker in the main window?

**Comment by jtackaberry** [comment]
I'm eager to see this rolled into the next release.  Is there anything preventing the pull request from being merged that I might be able to help with?

**Comment by swstim** [comment]
Thanks, merged and released with the new 2.9.5 prerelease.

**Comment by jtackaberry** [comment]
@swstim awesome, thanks!

**Comment by swstim** [comment]
@jtackaberry You're welcome.  Sorry for the delay, it's been an especially busy summer.

**Pull request merged**
