### PR TITLE
Version 2.12.1.1

### PR DESCRIPTION
**Pull request by cfillion**
~Preparing a hotfix update to 2.12.1.~ ~EDIT: Promoting that to a full bugfix update given the recent PRs.~ EDIT2: Reverting back to hotfix (+ trivial PRs) for quicker stable adoption.

---

### v2.12.1.1 pre-release build

Accessibility:

+ Support OSARA's shortcut help mode in cycle, continuous and MIDI editor actions

macOS:

+ Add macOS ARM64 build
+ Fix NF Eraser tool cursor not appearing (report here)

MIDI:

+ Fix MIDI CC shape loss after running any of the following actions (REAPER v6+ only, issue 1466):
    - SWS/BR: Delete tempo marker and preserve position and length of items (including MIDI events)
    - SWS/BR: Delete tempo marker and preserve position and length of selected items (including MIDI events)
    - SWS/BR: Enable "Ignore project tempo" for selected MIDI items preserving time position of MIDI events (use tempo at item's start)
+ Fix FNG MIDI actions treating only the first selected item in REAPER v6 (regression from v2.12.1, issue 1429)

Miscellaneous:

+ Fix SWS/AW: Paste not setting the time selection when "Trim contents behind media items when editing" is enabled (regression from v2.11)
+ Obey the "Move edit cursor when pasting/inserting media" preference in SWS/AW: Paste even when "Trim contents behind media items when editing" is disabled

ReaScript API:

+ Deprecate BR_GetMediaTrackGUID (use GetSetMediaTrackInfo_String from REAPER instead)
+ Deprecate ULT_GetMediaItemNote and ULT_SetMediaItemNote (use GetSetMediaItemInfo_String instead)
+ Fix fetching tracks from background project tabs using BR_GetMediaTrackByGUID
+ Fix generation of sws_python64.py
+ Preserve existing edges when passing negative values to BR_SetItemEdges (issue 1114)
+ Prevent NF_AnalyzeTakeLoudness's progress popup from stealing focus from other apps (report here)
+ Remove NF_ReadID3v2Tag (use GetMediaFileMetadata from REAPER instead)

### CODE REVIEW

**Comment by nofishonfriday** [comment]
@cfillion  Given that the reports about already fixed but not yet officially released issues seem to accumulate (e.g. [here](https://forum.cockos.com/showthread.php?p=2371087#post2371087) and [here](https://github.com/reaper-oss/sws/issues/1450)), how about making this PR into the next official release (soonish) and then continue working on the next beta?
I fear a little that if we're trying trying to release a 'bug free' major version it'll 'never happen'. :D

What do you think?

**Comment by cfillion** [comment]
I'd like to include some of the newer bugfixes too. The python64 one is major and the tag API must be removed before going stable. Then many PRs seem trivial enough to be low-risk (continuation of R6 CC shape support, the OSARA one, eraser tool cursor, track GUID...).

To go stable faster I'm considering leaving the .ini cycle action PRs for later.

**Comment by nofishonfriday** [comment]
whatsnew nitpick:
> Support OSARA's shortcut help mode in cycle, continuous and MIDI editor actions
could say:
Accessibility: Support...

(similar to the Reaper whatsnew entries related to accessibility topics)

**Comment by cfillion** [comment]
Planning to release this tomorrow.

**Comment by nofishonfriday** [comment]
What do you think about adding #1444?
It's a fix and seems rather risk free (at first glance)?

Otherwise, thumbs up!

**Comment by cfillion** [comment]
> What do you think about adding #1444?

Changing the meaning of "selected FX" from "the last FX shown in the chain" to "all selected FXs in the chain" makes me a bit hesitant. Only one action gets the new meaning, making it inconsistent with the other SWS actions dealing with "selected FX". I wrote some comments at https://github.com/reaper-oss/sws/issues/1443#issuecomment-721496647.

**Pull request merged**
