### PR TITLE
Add actions (Main section): "SWS: Select nearest previous folder", "SWS: Select nearest next folder"

### LINKED ISSUE #981: FR: "SWS: Select previous folder" and "SWS: Select next folder" to be a little smarter
Hi,

Currently, these two actions only work when a folder track is selected. Would it be possible to modify them so that if a user is on a standard track when they trigger the actions, they land on the nearest folder in either direction?

Example: let's say I have 12 drum tracks contained within a folder called "Drum bus", followed by two bass tracks which aren't folders, and below those, let's say 6 guitar tracks contained within a folder called "Guitar bus".

Currently, to navigate between those two folders using the SWS actions, I have to have one of the existing folders selected first. IE, if my snare track is selected, it's not possible to hit the keystroke I've bound to "SWS: Select next folder" and move to the "Guitar bus" folder.

This change would make folder navigation way more intuitive, and be massively appreciated by a whole bunch of blind users that I'm involved in putting a keymap together for.

Thanks for considering,

Scott

### PR DESCRIPTION
**Pull request by nofishonfriday**
closes #981 
Did these some time ago but forgot to submit, just noticed now when checking out X-Raym's pre-built.

### CODE REVIEW

**Comment by X-Raym** [comment]
@nofishonfriday 

I can't merge this to #1092 

In SourceTree:

```
git -c diff.mnemonicprefix=false -c core.quotepath=false merge github-desktop-nofishonfriday/Add_actions_-_Select_nearest_previous_folder
merge: github-desktop-nofishonfriday/Add_actions_-_Select_nearest_previous_folder - not something we can merge
```
Any idea ?

**Comment by nofishonfriday** [comment]
I assume it's because of the merge conflict in whatsnew.txt.
I've just updated the branch (reverting the changes in whatsnew.txt)
Pull the update and try merging again. Let me know.

**Comment by X-Raym** [comment]
@nofishonfriday It's all good now !

**Comment by nofishonfriday** [comment]
So my PR's are all merged now, yay.
Thanks!
Wow, it's quite a lot new stuff come together. :)
https://gist.github.com/nofishonfriday/fd1d23014a6b1504caefe289790986b3

**Pull request merged**
